<a href="https://colab.research.google.com/github/Xicotrainer/git-learning/blob/new_feature/tensor_data_camps.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
%tensorflow_version 2.x
import tensorflow as tf
print(tf.version)

<module 'tensorflow._api.v2.version' from '/usr/local/lib/python3.7/dist-packages/tensorflow/_api/v2/version/__init__.py'>


In [ ]:
#There are some scalars
string = tf.Variable("This is a string", tf.string)
number = tf.Variable(453, tf.int16)
floating = tf.Variable(2.71728182, tf.float64)

In [ ]:
print(string, "\n --->", type(string))


<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'This is a string'> 
 ---> <class 'tensorflow.python.ops.resource_variable_ops.ResourceVariable'>


In [ ]:
#There Now, we add an extra dimention to the tensor (getting a matrix)
rank2_tensor = tf.Variable([["Test_1", "Ok"], ["Test_2", "Reject"]], tf.string)
print(rank2_tensor, "\n ---------", type(rank2_tensor))

<tf.Variable 'Variable:0' shape=(2, 2) dtype=string, numpy=
array([[b'Test_1', b'Ok'],
       [b'Test_2', b'Reject']], dtype=object)> 
 --------- <class 'tensorflow.python.ops.resource_variable_ops.ResourceVariable'>


In [ ]:
# Analogous to shape, rank shows the tensor's dimention
tf.rank(rank2_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [ ]:
# Shape of Tensors
rank2_tensor.shape

TensorShape([2, 2])

In [ ]:
# Reshape case
tensor1 = tf.ones([1,2,3])
tensor1

<tf.Tensor: shape=(1, 2, 3), dtype=float32, numpy=
array([[[1., 1., 1.],
        [1., 1., 1.]]], dtype=float32)>

In [ ]:
tensor2 = tf.reshape(tensor1, [2,3,1])
tensor2

<tf.Tensor: shape=(2, 3, 1), dtype=float32, numpy=
array([[[1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.]]], dtype=float32)>

In [ ]:
tensor3 = tf.reshape(tensor1, [3, -1])
tensor3

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

In [ ]:
# Another example
t = tf.zeros([3,3,3])
t

<tf.Tensor: shape=(3, 3, 3), dtype=float32, numpy=
array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]], dtype=float32)>

In [ ]:
# Getting a vector
t = tf.reshape(t, [27])
t

<tf.Tensor: shape=(27,), dtype=float32, numpy=
array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>

In [ ]:
t = tf.reshape(t, [9,-1])
t

<tf.Tensor: shape=(9, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [ ]:
# Evaluating Tensors
with tf.Sssion() as sess:
  tensor.eval()

AttributeError: ignored

In [ ]:
# Anothe 

https://www.youtube.com/watch?v=tPYj3fFJGjk&t=1927s